# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Required by the release action
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Creates and releases a zip of the modpack in correct format.
      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dolf_old_tech.zip install_server.bat bin mods

      - name: List files
        run: ls -a

      - name: Upload to release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          file: dolf_old_tech.zip
          asset_name: dolf_old_tech.zip
          overwrite: true
          body: ""